swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/profile/{userId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transaction API
      description: API for fetching a user transactions datas
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: userId
          in: path
          required: true
          type: string
          description: Current user id
        - in: query
          name: currentMonth
          required: true
          type: string
          format: date-time
          description: Current month
      produces:
        - application/json
      responses:
        '200':
          description: User's transactions retrieved successully
          schema:
            $ref: '#/definitions/TransactionApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile/{userId}/transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transactions API
      description: API for fetching a user transactions details
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: userId
          required: true
          type: integer
          description: Current user id
        - in: path
          name: transactionId
          required: true
          type: integer
          description: Current transaction id 
      produces:
        - application/json
      responses:
        '200':
          description: Transaction details retrieved successully
          schema:
            $ref: '#/definitions/TransactionApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transactions API
      description: API for updating a user transactions transactions details
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: userId
          required: true
          type: integer
          description: Current user id
        - in: path
          name: transactionId
          required: true
          type: integer
          description: Current transaction id
        - in: body
          name: body
          description: Update user transaction details attributes
          required: true
          schema:
            $ref: '#/definitions/TransactionsDetails'
      produces:
        - application/json
      responses:
        '200':
          description: User transactions details updated successully
          schema:
            $ref: '#/definitions/TransactionApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: User Transactions API
      description: API for deleting a user transactions details
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: userId
          required: true
          type: integer
          description: Current user id
        - in: path
          name: transactionId
          required: true
          type: integer
          description: Current transaction id
        - in: body
          name: body
          description: Delete user transaction details attributes
          required: true
          schema:
            $ref: '#/definitions/TransactionsDetails'
      produces:
        - application/json
      responses:
        '200':
          description: User transactions details deleted successully
          schema:
            $ref: '#/definitions/TransactionApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  TransactionApiResponse:
    type: object
    properties: 
      status:
        type: integer
      message: 
        type: string
      body: 
        type: array
        items:
          type: object
          properties: 
            date: 
              type: string
            description: 
              type: string
            amount: 
              type: number
            balance: 
              type: number
            transactionType:
              type: string
            category:
              type: string
            notes:
              type: string
  TransactionsDetails:
    type: object
    properties: 
      category:
        type: string
      notes:
        type: string