swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/profile/transactions:
    post:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: User Transactions API
      description: API for fetching a user transactions datas
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: User's transaction retrieved successully
          schema:
            $ref: '#/definitions/TransactionsApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile/transactions/details:
    post:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: User Transactions API
      description: API for fetching a user transactions transaction details
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Transactions details retrieved successully
          schema:
            $ref: '#/definitions/DetailsApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: User Transactions API
      description: API for updating a user transactions transactions details
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update user transaction details attributes
          required: true
          schema:
            $ref: '#/definitions/TransactionsDetails'
      produces:
        - application/json
      responses:
        '200':
          description: User transactions details retrieved successully
          schema:
            $ref: '#/definitions/DetailsApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  TransactionsApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          type: object
          properties: 
            name: 
              type: string
            amount: 
              type : integer
            balance: 
              type: number
  DetailsApiResponse:
    type: object
    properties: 
      status:
        type: integer
      message: 
        type: string
      body: 
        type: array
        items:
          type: object
          properties: 
            date: 
              type: string
            description: 
              type: string
            amount: 
              type: number
            balance: 
              type: number
            transactionType:
              type: string
            category:
              type: string
            notes:
              type: string
  TransactionsDetails:
    type: object
    properties: 
      category:
        type: string
      notes:
        type: string